"use client";
import {useState} from "react";
type Screen="welcome"|"signup"|"portal"|"away"|"offline"|"queue"|"payment"|"audio"|"video"|"loading";
function Icon({children}:{children:React.ReactNode}){return <span className="icon">{children}</span>}
function Header({online=true,balance=0}:{online?:boolean,balance?:number}){return <header className="header"><div className="brand-mark">☾<span>✦</span></div><div className="brand">ALCHEMICAL<br/><b>VISIONS</b></div><div className="status"><span className={online?"dot online":"dot"}/>{online?"Online":"Offline"}</div><div className="balance"><strong>{balance.toFixed(2).replace(/^/,"$")}</strong><span>00:00:00</span><small>Remaining Balance</small></div></header>}
function Tabs({active,onChange}:{active:Screen,onChange:(s:Screen)=>void}){return <div className="tabs"><button className={active==="portal"?"tab active":"tab"} onClick={()=>onChange("portal")}><Icon>▤</Icon> Text Chat</button><button className={active==="video"?"tab active":"tab"} onClick={()=>onChange("video")}><Icon>◼</Icon> Video Chat</button><button className={active==="audio"?"tab active":"tab"} onClick={()=>onChange("audio")}><Icon>☎</Icon> Audio Call</button></div>}
function DecorativeSky({children}:{children:React.ReactNode}){return <div className="sky"><div className="stars">✦　✧　✦　☾　✦　✧　✦</div>{children}<div className="clouds">☁︎ ☁︎ ☁︎</div></div>}
function Field({icon,placeholder,type="text"}:{icon:string,placeholder:string,type?:string}){return <label className="field"><span>{icon}</span><input type={type} placeholder={placeholder}/></label>}
function Auth({signup,onBack,onPortal}:{signup:boolean,onBack:()=>void,onPortal:()=>void}){return <main className="app-shell narrow"><Header/><DecorativeSky><div className="hero-title">{signup?"Create Your Account":"Welcome"}</div><div className="subtitle">{signup?"Join Alchemical Visions":"Sign in to Continue"}</div><div className="crescent">☾</div></DecorativeSky><section className="form-card">{signup&&<Field icon="♙" placeholder="Username"/>}<Field icon="✉" placeholder="Email Address"/><Field icon="▣" placeholder="Password" type="password"/>{signup&&<><Field icon="▣" placeholder="Confirm Password" type="password"/><Field icon="♙" placeholder="Display Name (Optional)"/></>}{!signup&&<div className="remember"><span>☑ Remember Me</span><a>Forgot Password?</a></div>}<button className="gold-button" onClick={onPortal}>✦ {signup?"Create Account":"Sign In"} ✦</button><button className="light-button" onClick={onBack}>← Return Home</button></section></main>}
function BottomNav({onScreen}:{onScreen:(s:Screen)=>void}){return <><div className="nav-grid"><button><Icon>♙</Icon>Profile</button><button><Icon>▦</Icon>Schedule</button><button><Icon>▣</Icon>Book Followup<br/>Appointment</button><button><Icon>✉</Icon>Contact Me</button><button onClick={()=>onScreen("payment")}><Icon>▤</Icon>Billing Info</button><button><Icon>⚙</Icon>Settings</button></div><button className="purchase" onClick={()=>onScreen("payment")}>⌛　Purchase Additional Time　✦</button></>}
function CallPanel({audio=false,onEnd}:{audio?:boolean,onEnd:()=>void}){return <div className={audio?"call-panel audio":"call-panel video"}>{audio?<div className="phone-orb">☎</div>:<div className="video-avatar">●</div>}<div className="call-status">Your Call Is Connected</div><div className="timer">00:00:00</div><div className="call-controls"><button>🔊</button><button className="end-call" onClick={onEnd}>☎　End Call</button><button>{audio?"🎙":"▣"}</button></div></div>}
function Portal({screen,setScreen}:{screen:Screen,setScreen:(s:Screen)=>void}){return <main className="app-shell"><Header/><Tabs active={screen} onChange={setScreen}/><section className="main-panel">{screen==="portal"&&<><div className="chat-window"><div className="ornament">☀　✦　☾　✦　☀</div><p><b>Automated Portal Attendant:</b><br/>Your session will start momentarily. Please take the next five minutes to fill out the Profile section while you wait. You will not be charged until the session begins.</p><p><b>Automated Portal Attendant:</b><br/>Your session has started!</p><button className="end-call">☎　End Call</button></div><div className="message-row"><button className="round">⌕</button><input placeholder="Type a message..."/><button className="round">➤</button></div></>}{screen==="audio"&&<CallPanel audio onEnd={()=>setScreen("portal")}/>} {screen==="video"&&<CallPanel onEnd={()=>setScreen("portal")}/>}</section><BottomNav onScreen={setScreen}/></main>}
function StatusScreen({kind,setScreen}:{kind:"away"|"offline"|"queue",setScreen:(s:Screen)=>void}){const title=kind==="away"?"Alchemical Visions is Currently Away!":kind==="offline"?"Alchemical Visions is Currently Offline!":"In Queue";return <main className="app-shell"><Header online={kind!=="offline"}/><Tabs active="portal" onChange={setScreen}/><DecorativeSky><div className="status-title">{title}</div>{kind==="queue"?<><div className="wait">⌛</div><h2>Estimated Wait Time</h2><strong>&gt; 5 Minutes Remaining</strong><p>You are in line for the next available reader.</p></>:<><p>Provide your email address below if you&apos;d like to be notified when I&apos;m available.</p><div className="notify"><input placeholder="Email Address"/><button>Submit</button></div></>}<button className="gold-button">▦　Book Appointment</button></DecorativeSky><BottomNav onScreen={setScreen}/></main>}
function Payment({setScreen}:{setScreen:(s:Screen)=>void}){return <main className="app-shell narrow"><Header/><div className="payment-art"><div>☾</div><h1>Enter Your<br/>Payment Details</h1></div><section className="payment-form"><Field icon="▤" placeholder="Card Number"/><div className="split"><Field icon="▦" placeholder="MM / YY"/><Field icon="▣" placeholder="CVV"/></div><Field icon="♙" placeholder="Name on Card"/><label className="check">☑ Save this card for future sessions</label><button className="gold-button">▤　Pay & Start Session</button><button className="light-button" onClick={()=>setScreen("portal")}>← Back to Payment Options</button></section></main>}
export default function Home(){const[screen,setScreen]=useState<Screen>("welcome");if(screen==="welcome")return <main className="app-shell narrow"><Header/><DecorativeSky><div className="hero-title">Welcome</div><div className="subtitle">Sign in to Continue</div><div className="crescent">☾</div></DecorativeSky><section className="form-card"><button className="gold-button" onClick={()=>setScreen("portal")}>✦　Sign In　✦</button><button className="light-button" onClick={()=>setScreen("signup")}>♙＋　Create Your Account</button><button className="text-link" onClick={()=>setScreen("away")}>Preview Away / Offline States</button></section></main>;if(screen==="signup")return <Auth signup onBack={()=>setScreen("welcome")} onPortal={()=>setScreen("portal")}/>;if(screen==="away"||screen==="offline"||screen==="queue")return <StatusScreen kind={screen} setScreen={setScreen}/>;if(screen==="payment")return <Payment setScreen={setScreen}/>;return <Portal screen={screen} setScreen={setScreen}/>}